### ISSUE TITLE
Make Changes ♻️ 

### ISSUE THREAD

**Issue by karelvanoordt** [Somdotta07/Leaderboard#2]
https://github.com/Somdotta07/Leaderboard/blob/3610d2d4bdd84b55314c0129e3ca5b2012731fa7/src/index.html#L6

Good job so far with your code 💪  It looks great!

However, there are a few twitches you could make in order to make it look better.

- There's a typo in the title content. Don't forget to correct it.

**Comment by Somdotta07** [comment]
Thank you for the review :smiley:
I :hammer: the issue
